version: '3.8'

services:
  landing-page:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: landing-page-app
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      # Mount for development (optional - comment out for production)
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./styles.css:/usr/share/nginx/html/styles.css:ro
      - ./script.js:/usr/share/nginx/html/script.js:ro
    networks:
      - landing-page-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.docker.compose.project=landing-page"
      - "description=Modern Landing Page Application"

networks:
  landing-page-network:
    driver: bridge
    name: landing-page-net

# Optional: Add a reverse proxy for production
# nginx-proxy:
#   image: nginx:alpine
#   container_name: nginx-proxy
#   ports:
#     - "80:80"
#     - "443:443"
#   volumes:
#     - ./proxy.conf:/etc/nginx/nginx.conf:ro
#   depends_on:
#     - landing-page
#   networks:
#     - landing-page-network
